config/routes.rb
SampleApp::Application.routes.draw do
  resource :o_auth do
    member do
      get :strava
      get :instagram
      get :instagram_initiate_pubsub
      get :instagram_pubsub_callback
      post :instagram_pubsub_callback
    end
  end

  resources :users, only: [:show]

  root :to => 'website#home'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :firstname, :lastname, :profile_picture, :recent_ride_totals, :recent_run_totals
  attr_accessible :strava_uid, :strava_oauth

  def self.num_users
    Rails.cache.fetch('num_users') do
      User.count
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :calculate_num_users

  def calculate_num_users
    @num_users = User.num_users
  end
end

app/controllers/instagrams_controller.rb
class InstagramsController < ApplicationController

end

app/controllers/o_auths_controller.rb
class OAuthsController < ApplicationController
  def strava
    if params[:code]
      # Retrieve the access token.
      client_options = {site: Settings.strava.host, parse: :json}
      client = OAuth2::Client.new(Settings.strava.app_id, Settings.strava.app_secret, client_options)
      authorization = client.auth_code.get_token(params[:code])

      token = OAuth2::AccessToken.new(
        client,
        authorization.token,
        param_name: :access_token,
        mode: :query)

      myself = token.get('/api/v3/athlete').parsed
      myself = myself.inject({}){|memo,(k,v)| memo[k.to_sym] = v; memo}

      # create user if they do not exist.
      user = User.find_or_create_by_strava_uid(myself[:id].to_s)
      user.strava_oauth = authorization.token
      user.firstname = myself[:firstname]
      user.lastname = myself[:lastname]
      user.profile_picture = myself[:profile]
      user.save

      # update the user count cache
      Rails.cache.write('num_users', User.count)

      # redirect to the user's profile
      redirect_to(user_path(user))
    else
      @error = params[:error]
    end
  rescue OAuth2::Error => e
    @error = e
  end

  def instagram
    client_options = {
      site: Settings.instagram.host,
      redirect_uri: instagram_o_auth_url,
      authorize_url: '/oauth/authorize',
      token_url: '/oauth/access_token',
      parse: :json}
    client = OAuth2::Client.new(Settings.instagram.client_id, Settings.instagram.client_secret, client_options)
    authorization = client.auth_code.get_token(
      params[:code],
      redirect_uri: "#{Settings.host}#{instagram_o_auth_path}",
      parse: :json)

    user = User.find(1)
    user.instagram_access_token =  authorization.token
    user.instagram_uid = authorization['user']['id']
    user.instagram_username = authorization['user']['username']
    user.save!

    redirect_to(user_path(user))
  rescue OAuth2::Error => e
    puts e.inspect
  end

  def instagram_initiate_pubsub
    options = {
      body: {
        client_id: Settings.instagram.client_id,
        client_secret: Settings.instagram.client_secret,
        object: :user,
        aspect: :media,
        verify_token: :myVerifyToken,
        callback_url: "#{Settings.host}#{instagram_pubsub_callback_o_auth_path}"
      }
    }
    response = HTTParty.post('https://api.instagram.com/v1/subscriptions', options)
    puts response.body, response.code, response.message, response.headers.inspect
  end

  def instagram_pubsub_callback
    if request.get?
      mode = params['hub.mode']
      challenge = params['hub.challenge']
      verify_token = params['hub.verify_token']
      render(text: challenge) and return
    else
      #puts "POST REQUEST #{params}"
      data = params['_json']

      data.each do |media|
        puts "MEDIA #{media}"
      end

      render(text: 'OK') and return
    end
  end

  private

  # Generates an authorization URL.
  def authorize_url
    authorization_parameters = {
      response_type: 'code',
      redirect_uri:  instagram_o_auth_url,
      state:         'authorize_strava',
      access_type:   'offline'
    }
    config.auth_code.authorize_url(authorization_parameters)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

end

app/controllers/website_controller.rb
class WebsiteController < ApplicationController

  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
%html
  %head
    %title Strava Sample App
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    .navbar
      .navbar-inner
        %a.brand Strava Sample App
        %ul.nav
          %li.active= link_to('Home', root_path)
          %li
            - if @num_users == 0
              %a= "Be the first to sign up!"
            - elsif @num_users == 1
              %a= "#{@num_users} person has signed up!"
            - else
              %a= "#{@num_users} people have signed up!"

    .container
      .row
        = yield

app/views/o_auths/instagram.haml
%h1 Instagram callback

%p= link_to('Go back home.', root_path)

app/views/o_auths/strava.haml
%h1 Strava callback

- if @error
 %p= "Error: #{@error}"

%p= link_to('Go back home.', root_path)

app/views/users/show.haml
%h1= "Hi #{@user.firstname}, you've connected to the Strava API!"
%p That's it for this sample app for now.
%img{src: @user.profile_picture}

%p= link_to('Go back home.', root_path)

app/views/website/home.haml
%p
  = link_to(image_tag('connect-with-strava-large.png'), "#{Settings.strava.host}/oauth/authorize?approval_prompt=force&response_type=code&state=authorize_strava_sample_app&client_id=#{Settings.strava.app_id}&redirect_uri=#{strava_o_auth_url}&scope=write+view_private")

%p
  = link_to('Connect with Instagram', "#{Settings.instagram.host}/oauth/authorize?client_id=#{Settings.instagram.client_id}&redirect_uri=#{Settings.host}#{instagram_o_auth_path}&response_type=code&state=foo&access_type=offline")